---
name: AntiXrayPE
api: 5.0.0
version: 0.0.3
main: BeeAZZ\AntiXrayPE\Main
author: BeeAZ

commands:
  antixray:
    description: "Turn anti-xray mode on/off"
    aliases: ["ax", "antix"]
    permission: antixraype.check
permissions:
  antixraype.check:
    default: op
...
